# Generated by Django 5.0 on 2023-12-09 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('comments', '0001_initial'),
        ('petlisting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], default='pending', max_length=10)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seekeruser')),
                ('comments', models.ManyToManyField(blank=True, related_name='application_comment', to='comments.comment')),
                ('pet_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petlisting.petlisting')),
            ],
        ),
    ]
